### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by iiinsight** [alphadl/OOP-eval#1]
请问代码可以在Windows系统的conda虚拟环境中运行吗，我产生了多线程相关报错RuntimeError，无法继续执行：
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

在main_oop.py中加入
if __name__ == '__main__':
    sys.exit(main())

又产生报错：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\py38torch1101\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\Anaconda3\envs\py38torch1101\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)

EOFError: Ran out of input

请问应该怎么解决？

**Comment by wangzhe112-lab** [comment]
Hello, we are using the Ubuntu system. For issues occurring in the Windows environment, you can refer to:
1) https://github.com/Xiaoming-Yu/SingleGAN/issues/1 
2) https://github.com/NVlabs/MUNIT/issues/30
